# Generated by Django 4.2.11 on 2024-03-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion_oficio', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=7)),
                ('matricula', models.CharField(default='', max_length=40)),
                ('año', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Art',
                'verbose_name_plural': 'Art',
                'ordering': ['profesion_oficio'],
            },
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_del_auto', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=50)),
                ('modelo', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auto',
                'ordering': ['marca_del_auto'],
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='CoberturaParcial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=50)),
                ('responsabilidad_civil', models.CharField(max_length=10)),
                ('reposicion_0km', models.CharField(max_length=10)),
                ('daño_incendio_robototal', models.CharField(max_length=10)),
                ('daño_parcial_por_robo', models.CharField(max_length=10)),
                ('cerraduras', models.CharField(max_length=10)),
                ('cristales_laterales', models.CharField(max_length=10)),
                ('daños_por_granizo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Cuatro_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Dos_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Tres_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento_Un_Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=101, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=2500, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=2000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=1000, max_digits=20)),
                ('muerte_accidental', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('invalidez_parcial_total_permanente', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('gastos_asistencia_medica', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cubiertos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('año', models.IntegerField()),
                ('tipo_propiedad', models.CharField(choices=[('Departamento_Dos_Ambientes', 'Departamento_Dos_Ambientes'), ('Casa', 'Casa'), ('PH', 'PH'), ('Departamento_Tres_Ambientes', 'Departamento_Tres_Ambientes'), ('Departamento_Cuatro_Ambientes', 'Departamento_Cuatro_Ambientes')], max_length=30)),
            ],
            options={
                'verbose_name': 'Hogar',
                'verbose_name_plural': 'Hogar',
                'ordering': ['tipo_propiedad'],
            },
        ),
        migrations.CreateModel(
            name='Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=100, max_digits=20)),
                ('incendio', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('catastrofe_natural', models.DecimalField(decimal_places=2, default=1500000, max_digits=20)),
                ('reposicion_de_electrodomesticos', models.DecimalField(decimal_places=2, default=250000, max_digits=20)),
                ('robo', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
                ('daños_vivienda', models.DecimalField(decimal_places=2, default=2500000, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='TodoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=50)),
                ('responsabilidad_civil', models.CharField(max_length=10)),
                ('reposicion_0km', models.CharField(max_length=10)),
                ('daño_incendio_robototal', models.CharField(max_length=10)),
                ('daño_parcial_por_robo', models.CharField(max_length=10)),
                ('cerraduras', models.CharField(max_length=10)),
                ('cristales_laterales', models.CharField(max_length=10)),
                ('daños_por_granizo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoIndependiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=510, max_digits=3)),
                ('muerte_accidental', models.DecimalField(decimal_places=2, default=1500000, max_digits=8)),
                ('invalidez_parcial_total_permanente', models.DecimalField(decimal_places=2, default=1000000, max_digits=10)),
                ('gastos_asistencia_medica', models.DecimalField(decimal_places=2, default=150000, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('tipo_documento', models.CharField(choices=[('Documento Nacional de Identidad', 'Documento Nacional de Identidad'), ('Libreta Civica', 'Libreta Civica'), ('Libreta de Enrolamiento', 'Libreta de Enrolamiento'), ('CUIT', 'CUIT')], max_length=40)),
                ('n_numero', models.IntegerField(verbose_name=20)),
                ('n_celular', models.IntegerField(verbose_name=15)),
                ('correo_electronico', models.EmailField(max_length=40)),
                ('edad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vida',
                'verbose_name_plural': 'Vida',
                'ordering': ['nombre'],
            },
        ),
    ]
