# Generated by Django 4.2.11 on 2024-03-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vida',
            old_name='n_celular',
            new_name='numero_celular',
        ),
        migrations.RenameField(
            model_name='vida',
            old_name='n_numero',
            new_name='numero_doc',
        ),
    ]
